<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'name' => 'Rifqi Munawar',
                'nim' => '1',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'biografi saa',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'id' => 1,
                'role_id' => 1,
                'username' => 'rifqi_munawar',
                'slug' => 'rifqi_munawar',
                'email' => 'rifqimunawar@gmail.com',
                'password' => '$2y$10$v9PSngvVMqNJ3iG7GTHfou5Uips7dMgW27UMkiHo7Vh5m1GtRy3km',
                'email_verified_at' => NULL,
                'remember_token' => 'j9hIzfoVoZ2dPN7n0KQJn6nzXZ1xjhWd0RrF0YsTpeeEeGf4H1IfIMJNOM0u',
                'created_at' => '2023-06-12 15:28:30',
                'updated_at' => '2023-06-13 14:58:41',
                'centang' => '1',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            1 => 
            array (
                'name' => 'Superadmin',
                'nim' => '2',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'dzikir pikir amal shaleh',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'P',
                'id' => 2,
                'role_id' => 2,
                'username' => 'superadmin',
                'slug' => 'admin',
                'email' => 'superadmin@gmail.com',
                'password' => '$2y$10$hdNl.wU08YIdtydMIPyALeYMly/Qx9AiKJszYJCcuFMzWj/WT6kKa',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:28:30',
                'updated_at' => '2023-06-12 15:28:30',
                'centang' => '0',
                'rayon_id' => '2',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            2 => 
            array (
                'name' => 'admin',
                'nim' => '4',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'saya akan segera pkd',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'id' => 3,
                'role_id' => 2,
                'username' => 'admin',
                'slug' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$wuUX7iHsHPrvdEeqDQ5KCeYi.yS0Vi3gV.vhcIZEZ4h2SB165fIzu',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:28:31',
                'updated_at' => '2023-06-12 15:28:31',
                'centang' => '0',
                'rayon_id' => '3',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            3 => 
            array (
                'name' => 'user',
                'nim' => '5',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'id' => 4,
                'role_id' => 3,
                'username' => 'user',
                'slug' => 'user',
                'email' => 'user@gmail.com',
                'password' => '$2y$10$scwX9JDaCjFZiygW8Q1vGukfRe.DMF02UA2YFPibHB2DzAjc9kGqG',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:28:31',
                'updated_at' => '2023-06-12 15:28:31',
                'centang' => '0',
                'rayon_id' => '6',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            4 => 
            array (
                'name' => 'pengunjung',
                'nim' => '6',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'id' => 5,
                'role_id' => 4,
                'username' => 'pengunjung',
                'slug' => 'pengunjung',
                'email' => 'pengunjung@gmail.com',
                'password' => '$2y$10$2Pv3shNqGypTc1z8GSpRWOGpmw7.5J6EPA4ISJXwnrsDadqijNwWG',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:28:31',
                'updated_at' => '2023-06-12 15:28:31',
                'centang' => '0',
                'rayon_id' => '6',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            5 => 
            array (
                'name' => 'Raie Aswajjillah',
                'nim' => '41037006211028',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'id' => 6,
                'role_id' => 2,
                'username' => 'rai___a',
                'slug' => 'rai-a',
                'email' => 'rai010303@gmail.com',
                'password' => '$2y$10$ass8pGGsgs.pHslpRs11R.kbQPoxBO/9S9LXw7/R6sXE5A06RnyOS',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:28:31',
                'updated_at' => '2023-06-12 15:28:31',
                'centang' => '0',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            6 => 
            array (
                'name' => 'Ilyas Khoirul Alimnis',
                'nim' => '41037006211114',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'id' => 7,
                'role_id' => 3,
                'username' => 'Ilyas Khoirul A',
                'slug' => 'ilyas-khoirul-a',
                'email' => '',
                'password' => '$2y$10$MepGU6vnY1oYhhbrJph8R.088CtFZRIss687yIR9HVxyqe2C8HiCG',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:28:31',
                'updated_at' => '2023-06-12 15:28:31',
                'centang' => '0',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            7 => 
            array (
                'name' => 'Riki Ramdan',
                'nim' => '41037006191067',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'id' => 8,
                'role_id' => 2,
                'username' => 'rikiramdan25',
                'slug' => 'rikiramdan25',
                'email' => '',
                'password' => '$2y$10$gxg7TZHuYwEcQfbtuXs.1u/nTGQohgmjFayP7ND1wUGhGIEc8V9y2',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:28:31',
                'updated_at' => '2023-06-12 15:28:31',
                'centang' => '0',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            8 => 
            array (
                'name' => 'rifqi',
                'nim' => '12345678923456',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => NULL,
                'id' => 9,
                'role_id' => 4,
                'username' => 'rifqi',
                'slug' => 'rifqi',
                'email' => 'rifqimunawar48@gmail.com',
                'password' => '$2y$10$6xVwmw2ciVP9GpZdha04OOhmKLeUR039hqs9ie2Irwqd1H3rWL./O',
                'email_verified_at' => NULL,
                'remember_token' => 'G2vi6KNt3cRYV5ehA86IrkXUi8lVBE8uwO8KIEhODEK8G8aiBPTi0ZadQdtq',
                'created_at' => '2023-06-12 15:29:38',
                'updated_at' => '2023-06-13 14:44:06',
                'centang' => '0',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            9 => 
            array (
                'name' => 'rifqi',
                'nim' => '09090909090909',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => NULL,
                'id' => 10,
                'role_id' => 4,
                'username' => 'rifqi123',
                'slug' => 'rifqi123',
                'email' => 'rifqimunawar47@gmail.com',
                'password' => '$2y$10$JxxzxmW5kdjYPVoA60f9Y.nPBNsfSuU3Hq.n/IuQCWkdUAgEKM2OG',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-12 15:39:33',
                'updated_at' => '2023-06-12 15:39:33',
                'centang' => '0',
                'rayon_id' => '3',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
        ));
        
        
    }
}