<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PerpusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('perpus')->delete();
        
        \DB::table('perpus')->insert(array (
            0 => 
            array (
                'id' => 11,
                'judul' => 'HTML5 Notes For Professionals',
                'slug' => 'html5-notes-for-professionals',
                'penulis' => 'goalkicker.com',
                'penerbit' => 'goalkicker.com',
                'thn_terbit' => '2020',
                'isbn' => '-',
                'bahasa' => 'english',
                'halaman' => '176',
                'deskripsi' => 'Membahas mengenai cara pembuatan website dengan html 5',
                'categorybook_id' => 7,
                'user_id' => 1,
                'image' => 'perpus_-1685020274.png',
                'pdf' => 'perpus_-1685020274.pdf',
                'created_at' => '2023-05-25 13:11:14',
                'updated_at' => '2023-05-25 13:11:14',
            ),
            1 => 
            array (
                'id' => 12,
                'judul' => 'JavaScript Data Structures and Algorithms',
                'slug' => 'javascript-data-structures-and-algorithms',
                'penulis' => 'Sammie Bae',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'english',
                'halaman' => '351',
                'deskripsi' => 'JavaScript Data Structures and Algorithms',
                'categorybook_id' => 1,
                'user_id' => 1,
                'image' => 'perpus_-1685020510.png',
                'pdf' => 'perpus_-1685020510.pdf',
                'created_at' => '2023-05-25 13:15:12',
                'updated_at' => '2023-05-25 13:15:12',
            ),
            2 => 
            array (
                'id' => 13,
                'judul' => 'Benturan NU - PKI',
                'slug' => 'benturan-nu-pki',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '2013',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '159',
                'deskripsi' => '-',
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'perpus_Benturan NU - PKI-1685132485.jpg',
                'pdf' => 'perpus_Benturan NU - PKI-1685132485.pdf',
                'created_at' => '2023-05-26 20:21:25',
                'updated_at' => '2023-05-26 20:21:25',
            ),
            3 => 
            array (
                'id' => 14,
                'judul' => 'Analisis Sosial',
                'slug' => 'analisis-sosial',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '241',
                'deskripsi' => '-',
                'categorybook_id' => 1,
                'user_id' => 1,
                'image' => 'perpus_Analisis Sosial-1685132884.jpg',
                'pdf' => 'perpus_Analisis Sosial-1685132884.pdf',
                'created_at' => '2023-05-26 20:28:04',
                'updated_at' => '2023-05-26 20:28:04',
            ),
            4 => 
            array (
                'id' => 15,
                'judul' => 'Filsafat Ilmu',
                'slug' => 'filsafat-ilmu',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '2013',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '95',
                'deskripsi' => '-',
                'categorybook_id' => 2,
                'user_id' => 1,
                'image' => 'perpus_Filsafat Ilmu-1685133212.jpg',
                'pdf' => 'perpus_Filsafat Ilmu-1685133212.pdf',
                'created_at' => '2023-05-26 20:33:32',
                'updated_at' => '2023-05-26 20:33:32',
            ),
            5 => 
            array (
                'id' => 16,
                'judul' => 'Filsafat Islam',
                'slug' => 'filsafat-islam',
                'penulis' => 'Abdallah Baehaqi :v',
                'penerbit' => NULL,
                'thn_terbit' => NULL,
                'isbn' => NULL,
                'bahasa' => NULL,
                'halaman' => NULL,
                'deskripsi' => '!!إقرأ صحبة',
                'categorybook_id' => 2,
                'user_id' => 9,
                'image' => 'perpus_-1685192467.jpg',
                'pdf' => 'perpus_-1685192467.pdf',
                'created_at' => '2023-05-27 13:01:07',
                'updated_at' => '2023-05-27 13:01:07',
            ),
            6 => 
            array (
                'id' => 17,
                'judul' => 'Desain Grafis',
                'slug' => 'desain-grafis',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => '-',
                'halaman' => '100',
                'deskripsi' => '-',
                'categorybook_id' => 7,
                'user_id' => 1,
                'image' => 'Desain Grafis_PMII_UNINUS-1689006705.JPG',
                'pdf' => 'Desain Grafis-PMII_UNINUS1689006705.pdf',
                'created_at' => '2023-07-10 23:31:50',
                'updated_at' => '2023-07-10 23:31:50',
            ),
            7 => 
            array (
                'id' => 19,
                'judul' => 'Distilasi Alkena',
                'slug' => 'distilasi-alkena',
                'penulis' => 'Wira Nagara',
                'penerbit' => '-',
                'thn_terbit' => '2016',
                'isbn' => '-',
                'bahasa' => 'indonesia',
                'halaman' => '173',
                'deskripsi' => 'Distilasi Alkena adalah sebuah proses memisahkan dua hati yang pada dasarnya tak bisa dipisahkan karena suatu ikatan perasaan. Walaupun dalam perjalanannya, hati akan tumbuh untuk bisa merelakan.',
                'categorybook_id' => 3,
                'user_id' => 1,
                'image' => 'Distilasi Alkena_PMII_UNINUS-1689006977.JPG',
                'pdf' => 'Distilasi Alkena-PMII_UNINUS1689006977.pdf',
                'created_at' => '2023-07-10 23:36:17',
                'updated_at' => '2023-07-10 23:36:17',
            ),
            8 => 
            array (
                'id' => 21,
            'judul' => 'TEOLOGI ISLAM (DR. HARUN NASUTION)',
                'slug' => 'teologi-islam-dr-harun-nasution',
                'penulis' => 'DR. HARUN NASUTION',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '378-602-1602-08-7',
                'bahasa' => 'indonesia',
                'halaman' => '24',
                'deskripsi' => 'lmu kalam yang mendasari segala pokok pemikiran yang ada di dunia Islam yang kemudian menjadi  produk pemikiran yang banyak mewarnai kemajuan zaman.',
                'categorybook_id' => 4,
                'user_id' => 1,
            'image' => 'TEOLOGI ISLAM (DR. HARUN NASUTION)_PMII_UNINUS-1689007748.JPG',
            'pdf' => 'TEOLOGI ISLAM (DR. HARUN NASUTION)-PMII_UNINUS1689007748.pdf',
                'created_at' => '2023-07-10 23:49:08',
                'updated_at' => '2023-07-10 23:49:08',
            ),
            9 => 
            array (
                'id' => 22,
                'judul' => 'Hasil Muspimnas',
                'slug' => 'hasil-muspimnas',
                'penulis' => 'PMII',
                'penerbit' => 'PMII',
                'thn_terbit' => '2022',
                'isbn' => '378-602-1892-08-7',
                'bahasa' => 'indonesia',
                'halaman' => '400',
                'deskripsi' => 'Kegiatan Muspimnas PMII tahun 2022 sendiri direncanakan akan berlangsung di Tulungagung mulai tanggal 17 Nopember hingga 24 Nopember 2022',
                'categorybook_id' => 1,
                'user_id' => 1,
                'image' => 'Hasil Muspimnas_PMII_UNINUS-1689008089.JPG',
                'pdf' => NULL,
                'created_at' => '2023-07-10 23:54:49',
                'updated_at' => '2023-07-10 23:54:49',
            ),
            10 => 
            array (
                'id' => 23,
                'judul' => 'Teori-Teori Hukum',
                'slug' => 'teori-teori-hukum',
                'penulis' => 'Penulisnya ada di judul',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'indonesia',
                'halaman' => '233',
                'deskripsi' => NULL,
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Teori-Teori Hukum_PMII_UNINUS-1689008650.JPG',
                'pdf' => 'Teori-Teori Hukum-PMII_UNINUS1689008650.pdf',
                'created_at' => '2023-07-11 00:04:11',
                'updated_at' => '2023-07-11 00:04:11',
            ),
            11 => 
            array (
                'id' => 24,
                'judul' => 'Seperti Dendam, Rindu Harus Dibayar Tuntas',
                'slug' => 'seperti-dendam-rindu-harus-dibayar-tuntas',
                'penulis' => 'Eka Kurniawan',
                'penerbit' => 'Eka Kurniawan',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'indonesia',
                'halaman' => '254',
                'deskripsi' => 'Eka Kurniawan',
                'categorybook_id' => 3,
                'user_id' => 1,
                'image' => 'Seperti Dendam, Rindu Harus Dibayar Tuntas_PMII_UNINUS-1689008780.JPG',
                'pdf' => 'Seperti Dendam, Rindu Harus Dibayar Tuntas-PMII_UNINUS1689008780.pdf',
                'created_at' => '2023-07-11 00:06:22',
                'updated_at' => '2023-07-11 00:06:22',
            ),
            12 => 
            array (
                'id' => 25,
                'judul' => 'Sejarah Ideologi Dunia',
                'slug' => 'sejarah-ideologi-dunia',
                'penulis' => 'Nur Sayyid Santoso Kristeva, S.Pd.I, M.A.',
                'penerbit' => 'Nur Sayyid Santoso Kristeva, S.Pd.I, M.A.',
                'thn_terbit' => 'ya nda tau kok tanya saya',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '46',
                'deskripsi' => 'Sejarah Ideologi Dunia Kapitalisme, Sosialisme, Komunisme, Fasisme, Anarkisme, Anarkisme dan Marxisme, Konservatisme by Nur Sayyid Santoso Kristeva, S.Pd.I, M.A.',
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Sejarah Ideologi Dunia_PMII_UNINUS-1689009015.JPG',
                'pdf' => 'Sejarah Ideologi Dunia-PMII_UNINUS1689009015.pdf',
                'created_at' => '2023-07-11 00:10:15',
                'updated_at' => '2023-07-11 00:10:15',
            ),
            13 => 
            array (
                'id' => 26,
                'judul' => 'Sejarah Tuhan',
                'slug' => 'sejarah-tuhan',
                'penulis' => 'Karen Armstrong',
                'penerbit' => 'Mizan Pustaka',
                'thn_terbit' => '2014',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '280',
                'deskripsi' => 'Kisah 4.000 Tahun Pencarian Tuhan dalam Agama-Agama Manusia',
                'categorybook_id' => 2,
                'user_id' => 1,
                'image' => 'Sejarah Tuhan_PMII_UNINUS-1689009285.JPG',
                'pdf' => 'Sejarah Tuhan-PMII_UNINUS1689009285.pdf',
                'created_at' => '2023-07-11 00:14:46',
                'updated_at' => '2023-07-11 00:14:46',
            ),
            14 => 
            array (
                'id' => 27,
                'judul' => 'Sebuah Seni untuk Bersikap Bodo Amat',
                'slug' => 'sebuah-seni-untuk-bersikap-bodo-amat',
                'penulis' => 'by Mark Manson',
                'penerbit' => 'nda tau juga',
                'thn_terbit' => 'ya nda tau kok tanya saya',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '256',
                'deskripsi' => 'Sebuah Seni untuk Bersikap Bodo Amat adalah buku pertama karya Mark Manson, seorang narablog kenamaan dengan lebih dari 2 juta pembaca.',
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Sebuah Seni untuk Bersikap Bodo Amat_PMII_UNINUS-1689009522.JPG',
                'pdf' => 'Sebuah Seni untuk Bersikap Bodo Amat-PMII_UNINUS1689009522.pdf',
                'created_at' => '2023-07-11 00:18:45',
                'updated_at' => '2023-07-11 00:18:45',
            ),
            15 => 
            array (
                'id' => 28,
                'judul' => 'Retorika Aristoteles',
                'slug' => 'retorika-aristoteles',
                'penulis' => 'ga tau',
                'penerbit' => 'nda tau juga',
                'thn_terbit' => 'ya nda tau kok tanya saya',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '120',
                'deskripsi' => 'Retorika Aristoteles adalah risalah Yunani kuno tentang seni persuasi, yang berasal dari abad ke-4 SM',
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Retorika Aristoteles_PMII_UNINUS-1689009733.jpg',
                'pdf' => 'Retorika Aristoteles-PMII_UNINUS1689009733.pdf',
                'created_at' => '2023-07-11 00:22:13',
                'updated_at' => '2023-07-11 00:22:13',
            ),
            16 => 
            array (
                'id' => 29,
                'judul' => 'Orang-orang Di Persimpangan Kiri Jalan',
                'slug' => 'orang-orang-di-persimpangan-kiri-jalan',
                'penulis' => 'Soe Hok Gie',
                'penerbit' => 'ya nda tau kok tanya saya',
                'thn_terbit' => 'ya nda tau kok tanya saya',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '332',
                'deskripsi' => 'Orang-Orang Di Persimpangan Kiri Jalan salah satu karya Soe Hok Gie tentang pemberontakan PKI di Madiun ini dianyam demikian rupa seakan-akan kita membaca sebuah novel sejarah dramatis yang menegangkan',
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Orang-orang Di Persimpangan Kiri Jalan_PMII_UNINUS-1689010019.JPG',
                'pdf' => 'Orang-orang Di Persimpangan Kiri Jalan-PMII_UNINUS1689010019.pdf',
                'created_at' => '2023-07-11 00:27:05',
                'updated_at' => '2023-07-11 00:27:05',
            ),
            17 => 
            array (
                'id' => 30,
                'judul' => 'Perempuan Berbicara Kretek',
                'slug' => 'perempuan-berbicara-kretek',
                'penulis' => 'ga tau',
                'penerbit' => 'ya nda tau kok tanya saya',
                'thn_terbit' => 'ya nda tau kok tanya saya',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '334',
                'deskripsi' => 'Secara umum buku ini dibagi dalam empat bagian. Pertama, Ritus. Keseharian, di sini mereka bercerita tentang kehadiran kretek dalam keseharian mereka',
                'categorybook_id' => 6,
                'user_id' => 1,
                'image' => 'Perempuan Berbicara Kretek_PMII_UNINUS-1689010155.JPG',
                'pdf' => 'Perempuan Berbicara Kretek-PMII_UNINUS1689010155.pdf',
                'created_at' => '2023-07-11 00:29:18',
                'updated_at' => '2023-07-11 00:29:18',
            ),
            18 => 
            array (
                'id' => 31,
                'judul' => 'Nusa Jawa Silang Budaya',
                'slug' => 'nusa-jawa-silang-budaya',
                'penulis' => 'ga tau',
                'penerbit' => 'ya nda tau kok tanya saya',
                'thn_terbit' => 'ya nda tau kok tanya saya',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '358',
                'deskripsi' => 'silang budaya kajian sejarah terpadu / Denys Lombard ; alih bahasa, Winarsih Partaningrat Arifin, Rahayu S. Hidayat, Nini Hidayati Yusuf.',
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Nusa Jawa Silang Budaya_PMII_UNINUS-1689010294.JPG',
                'pdf' => 'Nusa Jawa Silang Budaya-PMII_UNINUS1689010294.pdf',
                'created_at' => '2023-07-11 00:31:39',
                'updated_at' => '2023-07-11 00:31:39',
            ),
            19 => 
            array (
                'id' => 32,
                'judul' => 'My Public Speaking',
                'slug' => 'my-public-speaking',
                'penulis' => 'Hilbram Dunar',
                'penerbit' => 'ya nda tau kok tanya saya',
                'thn_terbit' => 'ya nda tau kok tanya saya',
                'isbn' => 'ya nda tau kok tanya saya',
                'bahasa' => 'indonesia',
                'halaman' => '192',
                'deskripsi' => 'ditulis berdasarkan pengalaman Hilbram Dunar selama dua belas tahun menjadi seorang public speaker. Bermula sebagai penyiar di MS Tri FM,',
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'My Public Speaking_PMII_UNINUS-1689010388.JPG',
                'pdf' => 'My Public Speaking-PMII_UNINUS1689010388.pdf',
                'created_at' => '2023-07-11 00:33:09',
                'updated_at' => '2023-07-11 00:33:09',
            ),
            20 => 
            array (
                'id' => 33,
                'judul' => 'Aswaja',
                'slug' => 'aswaja',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '48',
                'deskripsi' => 'Buku panduan Aswaja PMII',
                'categorybook_id' => 1,
                'user_id' => 1,
                'image' => 'Aswaja_PMII_UNINUS-1689010820.jpg',
                'pdf' => 'Aswaja-PMII_UNINUS1689010820.pdf',
                'created_at' => '2023-07-11 00:40:20',
                'updated_at' => '2023-07-11 00:40:20',
            ),
            21 => 
            array (
                'id' => 34,
                'judul' => 'Negeri Para Bedebah',
                'slug' => 'negeri-para-bedebah',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '444',
                'deskripsi' => NULL,
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Negeri Para Bedebah_PMII_UNINUS-1689010940.jpg',
                'pdf' => 'Negeri Para Bedebah-PMII_UNINUS1689010940.pdf',
                'created_at' => '2023-07-11 00:42:24',
                'updated_at' => '2023-07-11 00:42:24',
            ),
            22 => 
            array (
                'id' => 35,
                'judul' => 'MADILOG',
                'slug' => 'madilog',
                'penulis' => 'Tan Malaka',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '388',
                'deskripsi' => NULL,
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'MADILOG_PMII_UNINUS-1689011080.jpg',
                'pdf' => 'MADILOG-PMII_UNINUS1689011080.pdf',
                'created_at' => '2023-07-11 00:44:41',
                'updated_at' => '2023-07-11 00:44:41',
            ),
            23 => 
            array (
                'id' => 36,
                'judul' => 'Seni Perang Sun Tzu',
                'slug' => 'seni-perang-sun-tzu',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '122',
                'deskripsi' => NULL,
                'categorybook_id' => 4,
                'user_id' => 1,
                'image' => 'Seni Perang Sun Tzu_PMII_UNINUS-1689011175.jpg',
                'pdf' => 'Seni Perang Sun Tzu-PMII_UNINUS1689011175.pdf',
                'created_at' => '2023-07-11 00:46:15',
                'updated_at' => '2023-07-11 00:46:15',
            ),
            24 => 
            array (
                'id' => 37,
                'judul' => 'Modul NDP',
                'slug' => 'modul-ndp',
                'penulis' => '-',
                'penerbit' => '-',
                'thn_terbit' => '-',
                'isbn' => '-',
                'bahasa' => 'Indonesia',
                'halaman' => '45',
                'deskripsi' => NULL,
                'categorybook_id' => 1,
                'user_id' => 1,
                'image' => 'Modul NDP_PMII_UNINUS-1689011537.jpg',
                'pdf' => 'Modul NDP-PMII_UNINUS1689011537.pdf',
                'created_at' => '2023-07-11 00:52:17',
                'updated_at' => '2023-07-11 00:52:17',
            ),
        ));
        
        
    }
}