<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Rifqi Munawar',
                'nim' => '1',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'biografi saa',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'role_id' => 1,
                'username' => 'rifqi_munawar',
                'slug' => 'rifqi_munawar',
                'email' => 'rifqimunawar@gmail.com',
                'password' => '$2y$10$A0toBTXKl3677uFqyBvBNOqGe6jEoLiKBLaAtQ/FPG.CR33l9URti',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '1',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Superadmin',
                'nim' => '2',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'dzikir pikir amal shaleh',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'P',
                'role_id' => 2,
                'username' => 'superadmin',
                'slug' => 'admin',
                'email' => 'superadmin@gmail.com',
                'password' => '$2y$10$3UEeyld4QC8NW4z6P2Zwy.6ksVRZE6ajUdw1.Nrp1OGZ3KbHruyhi',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '0',
                'rayon_id' => '2',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'admin',
                'nim' => '4',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'saya akan segera pkd',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'role_id' => 2,
                'username' => 'admin',
                'slug' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$nbJD.dIZEH07rEMsYevjBe4NYoFwCsJf26VbrM3whau/9RQxyrs.a',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '0',
                'rayon_id' => '3',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'user',
                'nim' => '5',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'role_id' => 3,
                'username' => 'user',
                'slug' => 'user',
                'email' => 'user@gmail.com',
                'password' => '$2y$10$.CcWXmaKTyc3rZp6DXV7sOTYOJtPjUm4PSTELF3dO4nRfZIIP6vou',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '0',
                'rayon_id' => '6',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'pengunjung',
                'nim' => '6',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'role_id' => 4,
                'username' => 'pengunjung',
                'slug' => 'pengunjung',
                'email' => 'pengunjung@gmail.com',
                'password' => '$2y$10$w.7gr2hoES1LRuo6m82g0e1PfvFhI51ze40lPikQh1kdCaY6uGS72',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '0',
                'rayon_id' => '6',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Raie Aswajjillah',
                'nim' => '41037006211028',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'role_id' => 2,
                'username' => 'rai___a',
                'slug' => 'rai-a',
                'email' => 'rai010303@gmail.com',
                'password' => '$2y$10$ass8pGGsgs.pHslpRs11R.kbQPoxBO/9S9LXw7/R6sXE5A06RnyOS',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '0',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Ilyas Khoirul Alimnis',
                'nim' => '41037006211114',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'role_id' => 3,
                'username' => 'Ilyas Khoirul A',
                'slug' => 'ilyas-khoirul-a',
                'email' => '',
                'password' => '$2y$10$MepGU6vnY1oYhhbrJph8R.088CtFZRIss687yIR9HVxyqe2C8HiCG',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '0',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Riki Ramdan',
                'nim' => '41037006191067',
                'img' => 'user.png',
                'provinces' => NULL,
                'cities' => NULL,
                'districts' => NULL,
                'villages' => NULL,
                'alamat' => NULL,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                't_lahir' => NULL,
                'ttl' => NULL,
                'hobi' => NULL,
                'sma' => NULL,
                'thn_lulus' => NULL,
                'thn_kuliah' => NULL,
                'wa' => NULL,
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'kelamin' => 'L',
                'role_id' => 2,
                'username' => 'rikiramdan25',
                'slug' => 'rikiramdan25',
                'email' => '',
                'password' => '$2y$10$gxg7TZHuYwEcQfbtuXs.1u/nTGQohgmjFayP7ND1wUGhGIEc8V9y2',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-06-19 07:19:17',
                'updated_at' => '2023-06-19 07:19:17',
                'centang' => '0',
                'rayon_id' => '1',
                'prodi' => NULL,
                'kaderisasi' => 'Belum Mapaba',
                'thn_mapaba' => NULL,
                'thn_pkd' => NULL,
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => NULL,
                'nonformal' => NULL,
            ),
        ));
        
        
    }
}